apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: remote-control-relay
  labels:
    app.kubernetes.io/name: remote-control-relay
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: remote-control-relay
