name: Bug report
description: Report a bug in CodexChat
title: "[Bug]: "
labels: ["bug", "needs-repro"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. For fastest triage, include deterministic repro details and environment outputs.

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you do, and what failed?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: doctor_output
    attributes:
      label: `CodexChatCLI doctor` output
      description: Run from `apps/CodexChatApp` and paste output.
      render: shell
      placeholder: |
        swift run CodexChatCLI doctor
        [OK] ...
    validations:
      required: true

  - type: textarea
    id: smoke_output
    attributes:
      label: `CodexChatCLI smoke` output
      description: Run from `apps/CodexChatApp` and paste output.
      render: shell
      placeholder: |
        swift run CodexChatCLI smoke
        Smoke check passed ...
    validations:
      required: true

  - type: textarea
    id: repro_details
    attributes:
      label: Repro details (`repro` fixture or minimal steps)
      description: Provide fixture name (`swift run CodexChatCLI repro --fixture <name>`) or the shortest manual repro steps.
      placeholder: |
        Fixture: basic-turn
        OR
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: host_path
    attributes:
      label: Host app verification
      description: Confirm whether this reproduces in the canonical host app path (`CodexChatHost` scheme).
      placeholder: |
        Reproduces in host app: yes/no
        Notes: ...

  - type: input
    id: environment
    attributes:
      label: Environment
      description: macOS, Xcode, and Codex CLI versions.
      placeholder: macOS 14.x, Xcode 16.x, codex x.y.z
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / diagnostics (optional)
      description: Paste relevant logs; redact secrets.
      render: shell
