name: Bug report
description: Report a bug in CodexChat
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please include as much detail as possible so we can reproduce.

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you do, and what went wrong?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      description: A minimal set of steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Diagnostics
      description: If possible, paste relevant logs (redact secrets) or attach a diagnostics bundle.
      render: shell

  - type: input
    id: environment
    attributes:
      label: Environment
      description: macOS version, Xcode version (if building), and Codex CLI version (if relevant).
      placeholder: macOS 14.x, Xcode 16.x, codex x.y.z

