name: Feature request
description: Propose an improvement or new feature for CodexChat
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Keep requests tied to a concrete user journey and architecture boundaries.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: As a user, I want...
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed solution
      description: What should change?
      placeholder: Describe a concrete approach...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other approaches considered...

  - type: checkboxes
    id: guardrails
    attributes:
      label: Guardrails
      options:
        - label: Preserves two-pane default UI (no persistent third pane).
          required: true
        - label: Fits host/CLI/shared module boundaries documented in `docs-public/ARCHITECTURE_CONTRACT.md`.
          required: true
