name: Feature request
description: Propose an improvement or new feature for CodexChat
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please keep requests focused and tied to a user journey.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: As a user, I want...
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed solution
      description: What do you think the solution should look like?
      placeholder: Describe a concrete approach...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other approaches you considered...

  - type: checkboxes
    id: guardrails
    attributes:
      label: Guardrails
      options:
        - label: This request preserves the two-pane default UI (no persistent third pane).
          required: true

