apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: remote-control-relay
  labels:
    app.kubernetes.io/name: remote-control-relay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: remote-control-relay
  minReplicas: 3
  maxReplicas: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 30
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
